// Real-time event names. All devices subscribe to rooms and refresh state on these events.
export const EVENTS = {
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  PAYMENT_WAITING: 'PAYMENT_WAITING',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  PAYMENT_STATUS: 'PAYMENT_STATUS',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  KITCHEN_NEW: 'KITCHEN_NEW',
  KITCHEN_PREPARING: 'KITCHEN_PREPARING',
  KITCHEN_UPDATED: 'KITCHEN_UPDATED',
  ORDER_READY: 'ORDER_READY',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  QUEUE_UPDATED: 'QUEUE_UPDATED',
  QUEUE_CALL: 'QUEUE_CALL',
  STOCK_UPDATED: 'STOCK_UPDATED',
  MENU_UPDATED: 'MENU_UPDATED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  PRINT_JOB_CREATED: 'PRINT_JOB_CREATED',
  PRINT_JOB_UPDATED: 'PRINT_JOB_UPDATED',
  PRINTER_STATUS: 'PRINTER_STATUS',
  PRINTER_ERROR: 'PRINTER_ERROR',
  KIOSK_STATUS: 'KIOSK_STATUS',
  STAFF_CALL: 'STAFF_CALL',
  AGENT_COMMAND: 'AGENT_COMMAND',
  // ---- theme park
  GATE_SCAN: 'GATE_SCAN',
  GATE_STATE: 'GATE_STATE',
  GATE_COMMAND: 'GATE_COMMAND',
  SECURITY_ALERT: 'SECURITY_ALERT',
  OCCUPANCY_UPDATED: 'OCCUPANCY_UPDATED',
  CAPACITY_ALERT: 'CAPACITY_ALERT',
  TICKET_UPDATED: 'TICKET_UPDATED',
  BOOKING_UPDATED: 'BOOKING_UPDATED',
  SALE_UPDATED: 'SALE_UPDATED',
  SALE_PAID: 'SALE_PAID',
  PARK_PAYMENT_WAITING: 'PARK_PAYMENT_WAITING',
  WALLET_UPDATED: 'WALLET_UPDATED',
  POINTS_UPDATED: 'POINTS_UPDATED',
  CREDENTIAL_UPDATED: 'CREDENTIAL_UPDATED',
  RIDE_UPDATED: 'RIDE_UPDATED',
  RIDE_SCAN: 'RIDE_SCAN',
  RIDE_QUEUE_UPDATED: 'RIDE_QUEUE_UPDATED',
  QUEUE_CALLED: 'QUEUE_CALLED',
  LOCKER_UPDATED: 'LOCKER_UPDATED',
  LOCKER_COMMAND: 'LOCKER_COMMAND',
  NOTIFICATION: 'NOTIFICATION',
  DEVICE_STATUS: 'DEVICE_STATUS',
  SHIFT_UPDATED: 'SHIFT_UPDATED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  MEMBER_UPDATED: 'MEMBER_UPDATED',
  DASHBOARD_TICK: 'DASHBOARD_TICK',
} as const;
export type EventName = (typeof EVENTS)[keyof typeof EVENTS];

export const rooms = {
  branchCashier: (branchId: string) => `branch:${branchId}:cashier`,
  branchKitchen: (branchId: string) => `branch:${branchId}:kitchen`,
  branchQueue: (branchId: string) => `branch:${branchId}:queue`,
  branchAdmin: (branchId: string) => `branch:${branchId}:admin`,
  branchKiosks: (branchId: string) => `branch:${branchId}:kiosks`,
  branchPrinters: (branchId: string) => `branch:${branchId}:printers`,
  kiosk: (kioskId: string) => `kiosk:${kioskId}`,
  agent: (agentId: string) => `agent:${agentId}`,
  device: (deviceId: string) => `device:${deviceId}`,
  global: 'global',
  // ---- theme park
  branchGates: (branchId: string) => `branch:${branchId}:gates`,
  branchRides: (branchId: string) => `branch:${branchId}:rides`,
  branchCounter: (branchId: string) => `branch:${branchId}:counter`,
  branchPublic: (branchId: string) => `branch:${branchId}:public`,
  gate: (gateId: string) => `gate:${gateId}`,
  ride: (rideId: string) => `ride:${rideId}`,
  scanPoint: (id: string) => `scanpoint:${id}`,
  locker: (branchId: string) => `branch:${branchId}:lockers`,
  account: (accountId: string) => `account:${accountId}`,
  booking: (bookingId: string) => `booking:${bookingId}`,
  sale: (saleId: string) => `sale:${saleId}`,
  parkDevice: (deviceId: string) => `pdevice:${deviceId}`,
};
